# Generated by Django 3.0.8 on 2020-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0002_auto_20200807_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='county',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactform',
            name='district',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
