# Generated by Django 3.0.8 on 2020-08-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0003_auto_20200808_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='gender_find',
            new_name='find_gender',
        ),
    ]
