# Generated by Django 3.0.8 on 2020-08-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0004_auto_20200808_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='passward',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
