# Generated by Django 3.0.8 on 2020-08-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0005_contactform_passward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=20)),
                ('card_msg', models.TextField(blank=True)),
                ('card_url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
