# Generated by Django 3.0.8 on 2020-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=20)),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('find_gender', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('county', models.CharField(blank=True, max_length=10)),
                ('district', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
