# Generated by Django 3.0.8 on 2020-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0011_auto_20200811_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='./static/img'),
        ),
    ]
