# Generated by Django 3.0.8 on 2020-08-16 19:32

import TOREAL.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0020_auto_20200815_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(storage=TOREAL.storage.ImageStorage(), upload_to='./static/user_image'),
        ),
    ]
