# Generated by Django 3.0.8 on 2020-08-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0021_auto_20200816_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
