# Generated by Django 3.0.8 on 2020-09-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TOREAL', '0022_user_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
